on:
  workflow_dispatch: # Manual trigger
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
  push:
    paths:
      - '.github/workflows/scheduled.yml'

      jobs:
  execute:
    runs-on: ubuntu-latest

    steps:
      - name: Display current date and time
        run: echo "The current date and time is $(date)"

